import { useEffect, useMemo, useState } from 'react';
import hospitals from '../data/hospitals.json';
import { SITE } from '../config/site';
import { useI18n } from '../i18n/i18nProvider';

const BOROUGHS = ['All Boroughs', 'Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'];
const LANGUAGE_NAMES = { en: 'English', ko: 'Korean', zh: 'Chinese', bn: 'Bengali', ur: 'Urdu' };
const AUDIO_COPY = {
  en: { play: 'Read in English', stop: 'Stop reading' },
  ko: { play: '영어로 읽기', stop: '읽기 중지' },
  zh: { play: '用英语朗读', stop: '停止朗读' },
  bn: { play: 'ইংরেজিতে পড়ুন', stop: 'পড়া বন্ধ করুন' },
  ur: { play: 'انگریزی میں پڑھیں', stop: 'پڑھنا بند کریں' },
};
const localDate = () => {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
};
const COPY = {
  en: { title:'Free Interpreter Help at New York Hospitals', intro:'New York general hospitals must provide meaningful language access. Make a request card you can show, save, print, email, or share before your visit.', lawTitle:'This is law—not a pending bill', lawText:'Signed December 10, 2025 and effective immediately. The law requires language assistance programs at New York general hospitals.', rightsTitle:'What you can ask for', rights:['A qualified interpreter at no cost','Your preferred language recorded in your medical record','Language help for appointments, care, billing, and discharge','Translated or explained important hospital forms','Communication support for hearing or vision needs','The Language Assistance Coordinator or Patient Representative'], makerTitle:'Make my hospital request card', makerHelp:'Choose an optional hospital and date. Nothing is sent to AAPICHECK.', hospital:'Hospital (optional)', noHospital:'No hospital selected', date:'Visit or request date', cardTitle:'LANGUAGE ASSISTANCE REQUEST', request:'I need a qualified interpreter.', free:'Please provide language assistance at no cost.', record:'Please record my preferred language in my medical record.', coordinator:'If help is not available, please contact the Language Assistance Coordinator or Patient Representative.', show:'Show full screen', print:'Print', download:'Download', email:'Email', share:'Share', speak:'Read aloud', hospitalsTitle:'Prepare for a hospital visit', hospitalsHelp:'These are featured NYC hospitals, not a verified compliance ranking. Call before visiting to confirm interpreter arrangements.', useHospital:'Use on my card', directions:'Directions', statewide:'Find hospitals statewide', all:'All Boroughs', selected:'Selected', problemTitle:'If you do not receive language help', steps:['Ask again for a qualified interpreter','Ask for the Language Assistance Coordinator or Patient Representative','Write down the date, department, and what happened','Use the hospital complaint process','If unresolved, contact the New York State Department of Health'], rightsLink:'Official NYS patient rights', lawLink:'Official law record', disclaimer:'AAPICHECK provides a visit-preparation tool, not legal advice or an official government form. General-hospital coverage and individual circumstances may vary.' },
  ko: { title:'뉴욕 병원 무료 통역·언어지원', intro:'뉴욕주 일반병원은 의미 있는 언어 접근을 제공해야 합니다. 방문 전에 보여주거나 저장·인쇄·이메일·공유할 요청 카드를 만드세요.', lawTitle:'계류 법안이 아니라 시행 중인 법입니다', lawText:'2025년 12월 10일 서명되어 즉시 발효되었습니다. 뉴욕주 일반병원에 언어지원 프로그램을 요구합니다.', rightsTitle:'요청할 수 있는 지원', rights:['무료 자격 통역사','선호 언어를 의료 기록에 표시','예약·진료·청구·퇴원 안내의 언어 지원','중요 병원 서류의 번역 또는 설명','청각·시각 지원이 필요한 경우 의사소통 지원','언어지원 코디네이터 또는 환자 담당자 연결'], makerTitle:'병원 요청 카드 만들기', makerHelp:'병원과 날짜는 선택 사항입니다. 정보는 AAPICHECK로 전송되지 않습니다.', hospital:'병원(선택 사항)', noHospital:'병원을 선택하지 않음', date:'방문 또는 요청 날짜', cardTitle:'언어 지원 요청', request:'한국어 자격 통역사가 필요합니다.', free:'무료 언어 지원을 제공해 주세요.', record:'제 선호 언어를 의료 기록에 기록해 주세요.', coordinator:'도움을 받을 수 없다면 언어지원 코디네이터 또는 환자 담당자에게 연결해 주세요.', show:'전체 화면', print:'인쇄', download:'다운로드', email:'이메일', share:'공유', speak:'소리 내어 읽기', hospitalsTitle:'병원 방문 준비', hospitalsHelp:'아래는 NYC 주요 병원이며 준수 인증 순위가 아닙니다. 방문 전에 통역 방식과 도착 안내를 전화로 확인하세요.', useHospital:'카드에 사용', directions:'길 찾기', statewide:'뉴욕주 전체 병원 찾기', all:'모든 자치구', selected:'선택됨', problemTitle:'언어 지원을 받지 못했을 때', steps:['자격 통역사를 다시 요청하세요','언어지원 코디네이터 또는 환자 담당자를 요청하세요','날짜·부서·상황을 기록하세요','병원 고충처리 절차를 이용하세요','해결되지 않으면 뉴욕주 보건부에 연락하세요'], rightsLink:'NYS 공식 환자 권리', lawLink:'공식 법률 기록', disclaimer:'AAPICHECK는 병원 방문 준비 도구이며 법률 자문이나 정부 공식 양식이 아닙니다. 일반병원 적용 범위와 개인 상황은 다를 수 있습니다.' },
  zh: { title:'纽约医院免费口译与语言协助', intro:'纽约州综合医院必须提供有意义的语言服务。请制作一张可在就诊时出示、保存、打印、电邮或分享的请求卡。', lawTitle:'这已是法律，不是待审议法案', lawText:'该法于2025年12月10日签署并立即生效，要求纽约综合医院建立语言协助计划。', rightsTitle:'您可以要求', rights:['免费合格口译员','在病历中记录您的首选语言','预约、诊疗、账单和出院说明的语言协助','重要医院表格的翻译或解释','听力或视力沟通支持','联系语言协助协调员或患者代表'], makerTitle:'制作医院请求卡', makerHelp:'医院和日期为可选项。信息不会发送给AAPICHECK。', hospital:'医院（可选）', noHospital:'未选择医院', date:'就诊或请求日期', cardTitle:'语言协助请求', request:'我需要合格的中文口译员。', free:'请免费提供语言协助。', record:'请在我的病历中记录首选语言。', coordinator:'若无法提供帮助，请联系语言协助协调员或患者代表。', show:'全屏显示', print:'打印', download:'下载', email:'电邮', share:'分享', speak:'朗读', hospitalsTitle:'准备医院就诊', hospitalsHelp:'以下为部分纽约市医院，并非合规认证排名。请在就诊前电话确认口译安排。', useHospital:'用于请求卡', directions:'路线', statewide:'查找全州医院', all:'所有行政区', selected:'已选择', problemTitle:'如果没有获得语言协助', steps:['再次要求合格口译员','要求联系语言协助协调员或患者代表','记录日期、部门和情况','使用医院投诉程序','若未解决，请联系纽约州卫生厅'], rightsLink:'NYS官方患者权利', lawLink:'官方法律记录', disclaimer:'AAPICHECK是就诊准备工具，不是法律建议或政府官方表格。综合医院的适用范围及个人情况可能不同。' },
  bn: { title:'নিউ ইয়র্ক হাসপাতালে বিনামূল্যে দোভাষী সহায়তা', intro:'নিউ ইয়র্কের সাধারণ হাসপাতালগুলোকে ভাষা সহায়তা দিতে হয়। দেখানো, সংরক্ষণ, প্রিন্ট, ইমেইল বা শেয়ারের জন্য অনুরোধ কার্ড তৈরি করুন।', lawTitle:'এটি এখন আইন—অপেক্ষমাণ বিল নয়', lawText:'১০ ডিসেম্বর ২০২৫ স্বাক্ষরিত হয়ে সঙ্গে সঙ্গে কার্যকর হয়েছে।', rightsTitle:'আপনি যা চাইতে পারেন', rights:['বিনামূল্যে যোগ্য দোভাষী','মেডিকেল রেকর্ডে পছন্দের ভাষা লেখা','অ্যাপয়েন্টমেন্ট, চিকিৎসা, বিল ও ছাড়পত্রে ভাষা সহায়তা','গুরুত্বপূর্ণ ফর্মের অনুবাদ বা ব্যাখ্যা','শ্রবণ বা দৃষ্টির যোগাযোগ সহায়তা','ভাষা সহায়তা সমন্বয়কারী বা রোগী প্রতিনিধি'], makerTitle:'হাসপাতাল অনুরোধ কার্ড তৈরি করুন', makerHelp:'হাসপাতাল ও তারিখ ঐচ্ছিক। তথ্য AAPICHECK-এ পাঠানো হয় না।', hospital:'হাসপাতাল (ঐচ্ছিক)', noHospital:'হাসপাতাল নির্বাচন করা হয়নি', date:'ভিজিটের তারিখ', cardTitle:'ভাষা সহায়তার অনুরোধ', request:'আমার একজন যোগ্য বাংলা দোভাষী প্রয়োজন।', free:'বিনামূল্যে ভাষা সহায়তা দিন।', record:'আমার পছন্দের ভাষা মেডিকেল রেকর্ডে লিখুন।', coordinator:'সহায়তা না পেলে ভাষা সহায়তা সমন্বয়কারী বা রোগী প্রতিনিধিকে ডাকুন।', show:'পূর্ণ পর্দা', print:'প্রিন্ট', download:'ডাউনলোড', email:'ইমেইল', share:'শেয়ার', speak:'পড়ে শোনান', hospitalsTitle:'হাসপাতাল ভিজিটের প্রস্তুতি', hospitalsHelp:'এগুলো নির্বাচিত NYC হাসপাতাল, যাচাইকৃত সম্মতি র‍্যাঙ্কিং নয়। যাওয়ার আগে ফোন করুন।', useHospital:'কার্ডে ব্যবহার', directions:'দিকনির্দেশ', statewide:'রাজ্যজুড়ে হাসপাতাল খুঁজুন', all:'সব বরো', selected:'নির্বাচিত', problemTitle:'ভাষা সহায়তা না পেলে', steps:['আবার যোগ্য দোভাষী চান','সমন্বয়কারী বা রোগী প্রতিনিধি চান','তারিখ, বিভাগ ও ঘটনা লিখুন','হাসপাতালের অভিযোগ প্রক্রিয়া ব্যবহার করুন','সমাধান না হলে NYS স্বাস্থ্য বিভাগে যোগাযোগ করুন'], rightsLink:'NYS রোগীর সরকারি অধিকার', lawLink:'সরকারি আইন রেকর্ড', disclaimer:'AAPICHECK ভিজিট প্রস্তুতির টুল; আইনি পরামর্শ বা সরকারি ফর্ম নয়।' },
  ur: { title:'نیویارک ہسپتالوں میں مفت مترجم کی مدد', intro:'نیویارک کے جنرل ہسپتالوں کو زبان کی سہولت دینی لازم ہے۔ دکھانے، محفوظ کرنے، پرنٹ، ای میل یا شیئر کے لیے درخواست کارڈ بنائیں۔', lawTitle:'یہ قانون ہے، زیرِ التوا بل نہیں', lawText:'10 دسمبر 2025 کو دستخط کے بعد فوراً نافذ ہوا۔', rightsTitle:'آپ کیا مانگ سکتے ہیں', rights:['مفت مستند مترجم','میڈیکل ریکارڈ میں پسندیدہ زبان','اپائنٹمنٹ، علاج، بل اور ڈسچارج میں مدد','اہم فارم کا ترجمہ یا وضاحت','سماعت یا بصارت کے لیے رابطے کی مدد','زبان معاونت کوآرڈینیٹر یا مریض نمائندہ'], makerTitle:'ہسپتال درخواست کارڈ بنائیں', makerHelp:'ہسپتال اور تاریخ اختیاری ہیں۔ معلومات AAPICHECK کو نہیں بھیجی جاتیں۔', hospital:'ہسپتال (اختیاری)', noHospital:'کوئی ہسپتال منتخب نہیں', date:'وزٹ کی تاریخ', cardTitle:'زبان کی معاونت کی درخواست', request:'مجھے ایک مستند اردو مترجم درکار ہے۔', free:'براہ کرم مفت زبان کی سہولت دیں۔', record:'میری پسندیدہ زبان میڈیکل ریکارڈ میں درج کریں۔', coordinator:'مدد نہ ملے تو کوآرڈینیٹر یا مریض نمائندے کو بلائیں۔', show:'پوری اسکرین', print:'پرنٹ', download:'ڈاؤن لوڈ', email:'ای میل', share:'شیئر', speak:'آواز میں پڑھیں', hospitalsTitle:'ہسپتال وزٹ کی تیاری', hospitalsHelp:'یہ منتخب NYC ہسپتال ہیں، تصدیق شدہ تعمیل کی درجہ بندی نہیں۔ جانے سے پہلے فون کریں۔', useHospital:'کارڈ میں استعمال', directions:'راستہ', statewide:'ریاست بھر کے ہسپتال', all:'تمام بورو', selected:'منتخب', problemTitle:'اگر زبان کی مدد نہ ملے', steps:['دوبارہ مستند مترجم مانگیں','کوآرڈینیٹر یا مریض نمائندہ مانگیں','تاریخ، شعبہ اور واقعہ لکھیں','ہسپتال کی شکایت کا طریقہ استعمال کریں','مسئلہ حل نہ ہو تو NYS محکمہ صحت سے رابطہ کریں'], rightsLink:'NYS مریض کے سرکاری حقوق', lawLink:'سرکاری قانون ریکارڈ', disclaimer:'AAPICHECK تیاری کا ذریعہ ہے، قانونی مشورہ یا سرکاری فارم نہیں۔' },
};

function HospitalCompliance() {
  const { lang } = useI18n(); const c = COPY[lang] || COPY.en;
  const [borough,setBorough]=useState('All Boroughs'); const [hospitalId,setHospitalId]=useState('');
  const [visitDate,setVisitDate]=useState(localDate); const [fullScreen,setFullScreen]=useState(false); const [reading,setReading]=useState(false);
  const selected=hospitals.find(h=>String(h.id)===hospitalId); const filtered=useMemo(()=>borough==='All Boroughs'?hospitals:hospitals.filter(h=>h.borough===borough),[borough]);
  useEffect(()=>{document.title=`${c.title} — ${SITE.name}`;},[c.title]);
  useEffect(()=>{const close=e=>e.key==='Escape'&&setFullScreen(false);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
  useEffect(()=>()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel();},[]);
  const english=`I need a qualified ${LANGUAGE_NAMES[lang] || 'language'} interpreter. Please provide language assistance at no cost. Please record my preferred language in my medical record.`;
  const cardText=[c.cardTitle,selected?.name,visitDate,'',c.request,c.free,c.record,c.coordinator,'','English:',english,'','S6288B/A387B · Chapter 614'].filter(Boolean).join('\n');
  const download=()=>{const u=URL.createObjectURL(new Blob([cardText],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`AAPICHECK-language-request-${visitDate}.txt`;a.click();URL.revokeObjectURL(u);};
  const share=async()=>{if(navigator.share)await navigator.share({title:c.cardTitle,text:cardText});else await navigator.clipboard.writeText(cardText);};
  const speak=()=>{if(!('speechSynthesis'in window))return;if(reading){window.speechSynthesis.cancel();setReading(false);return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(english);u.lang='en-US';u.onend=()=>setReading(false);u.onerror=()=>setReading(false);setReading(true);window.speechSynthesis.speak(u);};
  return <section className="language-help page-enter">
    <header className="language-help__hero"><div><p className="eyebrow">S6288B / A387B · CHAPTER 614</p><h1>{c.title}</h1><p>{c.intro}</p><div className="button-row"><a className="btn btn--primary" href="#request-card">{c.makerTitle}</a><a className="btn btn--secondary" href="#hospitals">{c.hospitalsTitle}</a></div></div><aside><strong>✓ {c.lawTitle}</strong><p>{c.lawText}</p><a href="https://www.nysenate.gov/legislation/bills/2025/S6288/amendment/B" target="_blank" rel="noreferrer">{c.lawLink} ↗</a></aside></header>
    <section className="language-rights"><h2>{c.rightsTitle}</h2><ul>{c.rights.map(x=><li key={x}><span aria-hidden="true">✓</span>{x}</li>)}</ul></section>
    <section id="request-card" className="request-maker"><div className="request-maker__form"><p className="eyebrow">AAPICHECK</p><h2>{c.makerTitle}</h2><p>{c.makerHelp}</p><label>{c.hospital}<select value={hospitalId} onChange={e=>setHospitalId(e.target.value)}><option value="">{c.noHospital}</option>{hospitals.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select></label><label>{c.date}<input type="date" value={visitDate} onChange={e=>setVisitDate(e.target.value)}/></label></div>
      <article className={`visit-language-card${fullScreen?' visit-language-card--fullscreen':''}`} role={fullScreen?'dialog':undefined} aria-modal={fullScreen||undefined}>{fullScreen&&<button className="visit-language-card__close" type="button" onClick={()=>setFullScreen(false)} aria-label="Close">×</button>}<p className="visit-language-card__brand">AAPICHECK</p><h2>{c.cardTitle}</h2>{selected&&<strong>{selected.name}</strong>}<time dateTime={visitDate}>{visitDate}</time><div className="visit-language-card__request"><p>{c.request}</p><p>{c.free}</p><p>{c.record}</p><p>{c.coordinator}</p></div>{lang!=='en'&&<div className="visit-language-card__english" lang="en"><strong>English</strong><p>{english}</p></div>}<small>New York hospital language assistance · S6288B/A387B, Chapter 614</small></article>
      <div className="card-actions"><button type="button" onClick={()=>setFullScreen(true)}>⛶ {c.show}</button><button type="button" onClick={()=>window.print()}>▣ {c.print}</button><button type="button" onClick={download}>↓ {c.download}</button><button type="button" onClick={()=>{window.location.href=`mailto:?subject=${encodeURIComponent(c.cardTitle)}&body=${encodeURIComponent(cardText)}`;}}>@ {c.email}</button><button type="button" onClick={share}>↗ {c.share}</button><button type="button" aria-pressed={reading} onClick={speak}>{reading?'■':'▶'} {(AUDIO_COPY[lang]||AUDIO_COPY.en)[reading?'stop':'play']}</button></div>
    </section>
    <section id="hospitals" className="language-hospitals"><div className="section-heading"><h2>{c.hospitalsTitle}</h2><p>{c.hospitalsHelp}</p><a className="text-link" href="/map">{c.statewide} →</a></div><div className="directory__filters">{BOROUGHS.map(x=><button type="button" key={x} className={`chip ${borough===x?'chip--active':''}`} aria-pressed={borough===x} onClick={()=>setBorough(x)}>{x==='All Boroughs'?c.all:x}</button>)}</div><div className="compliance__grid">{filtered.map(h=><article className="glass-card compliance-card" key={h.id}><div className="compliance-card__header"><div><h3 className="compliance-card__name">{h.name}</h3><p className="compliance-card__borough">{h.address}</p></div><span className="badge badge--teal">{h.borough}</span></div><div className="button-row"><button type="button" className="btn btn--primary" onClick={()=>{setHospitalId(String(h.id));document.querySelector('#request-card')?.scrollIntoView({behavior:'smooth'});}}>{hospitalId===String(h.id)?`✓ ${c.selected}`:c.useHospital}</button><a className="btn btn--secondary" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(h.address)}`} target="_blank" rel="noreferrer">{c.directions}</a></div></article>)}</div></section>
    <section className="language-problem"><h2>{c.problemTitle}</h2><ol>{c.steps.map(x=><li key={x}>{x}</li>)}</ol><div className="button-row"><a className="btn btn--primary" href="https://www.health.ny.gov/publications/1500/" target="_blank" rel="noreferrer">{c.rightsLink}</a><a className="btn btn--secondary" href="mailto:hospinfo@health.ny.gov">hospinfo@health.ny.gov</a></div></section><p className="language-help__disclaimer">{c.disclaimer}</p>
  </section>;
}
export default HospitalCompliance;
